export const SET_DRIVER = "SET_DRIVER";

export const ADD_APPOINTMENT = "ADD_APPOINTMENT";
export const EDIT_APPOINTMENT = "EDIT_APPOINTMENT";
export const DELETE_APPOINTMENT = "DELETE_APPOINTMENT";

export const SET_ERRORS = "SET_ERRORS";
